#!/usr/bin/env python3
"""
finops/scripts/generate-optimization-pr.py
Generate Kustomize patch files and a complete PR description from VPA recommendations.

Example generated patch:
  # Generated by finops/scripts/generate-optimization-pr.py
  # VPA recommendation for api-gateway in namespace production
  # Expected savings: $47.20/month (32% reduction)
  # Evidence: kubectl get vpa api-gateway -n production -o yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-gateway
    namespace: production
  spec:
    template:
      spec:
        containers:
          - name: api-gateway
            resources:
              requests:
                cpu: "250m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

DEFAULT_CPU_HOURLY_RATE_USD = 0.048
DEFAULT_MEMORY_GIB_HOURLY_RATE_USD = 0.006

# <-- CHANGE THIS: Set to your Kubecost/OpenCost service URL.
# Valid values: an http(s) base URL like http://kubecost.finops.svc.cluster.local:9090.
# Find this in your cluster/service setup documented in finops/docs/installation.md.
DEFAULT_KUBECOST_URL = "http://kubecost.finops.svc.cluster.local:9090"


def parse_cpu(cpu: str | None) -> float:
    if not cpu:
        return 0.0
    value = str(cpu).strip()
    if value.endswith("m"):
        return float(value[:-1]) / 1000.0
    return float(value)


def parse_memory_gib(memory: str | None) -> float:
    if not memory:
        return 0.0
    value = str(memory).strip()
    units = {
        "Ki": 1 / (1024 * 1024),
        "Mi": 1 / 1024,
        "Gi": 1,
        "Ti": 1024,
    }
    for suffix, factor in units.items():
        if value.endswith(suffix):
            return float(value[: -len(suffix)]) * factor
    return float(value) / (1024**3)


def format_cpu(cores: float) -> str:
    if cores <= 0:
        return "0"
    milli = int(round(cores * 1000))
    return f"{milli}m" if milli < 1000 else f"{cores:.3f}".rstrip("0").rstrip(".")


def format_memory_gib(gib: float) -> str:
    if gib <= 0:
        return "0Mi"
    mib = int(round(gib * 1024))
    return f"{mib}Mi"


def run_json(cmd: list[str]) -> dict[str, Any]:
    out = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return json.loads(out.stdout)


def fetch_vpas(namespace: str) -> list[dict[str, Any]]:
    payload = run_json(["kubectl", "get", "vpa", "-n", namespace, "-o", "json"])
    return payload.get("items", [])


def fetch_deployment(namespace: str, name: str) -> dict[str, Any]:
    return run_json(["kubectl", "get", "deployment", name, "-n", namespace, "-o", "json"])


def fetch_pdbs(namespace: str) -> list[dict[str, Any]]:
    payload = run_json(["kubectl", "get", "pdb", "-n", namespace, "-o", "json"])
    return payload.get("items", [])


def fetch_pricing(kubecost_url: str) -> dict[str, float]:
    try:
        import requests  # noqa: PLC0415

        resp = requests.get(f"{kubecost_url}/model/node/pricing", timeout=20)
        resp.raise_for_status()
        nodes = resp.json().get("data", {}).get("nodes", [])
        if not nodes:
            raise ValueError("no node pricing in response")
        cpu_rates = [float(n.get("cpuHourlyCost", DEFAULT_CPU_HOURLY_RATE_USD)) for n in nodes]
        mem_rates = [
            float(n.get("ramGBHourlyCost", DEFAULT_MEMORY_GIB_HOURLY_RATE_USD)) for n in nodes
        ]
        return {
            "cpu": sum(cpu_rates) / len(cpu_rates),
            "memory": sum(mem_rates) / len(mem_rates),
            "source": "kubecost",
        }
    except Exception as exc:  # noqa: BLE001
        print(f"WARNING: falling back to default pricing: {exc}", file=sys.stderr)
        return {
            "cpu": DEFAULT_CPU_HOURLY_RATE_USD,
            "memory": DEFAULT_MEMORY_GIB_HOURLY_RATE_USD,
            "source": "defaults",
        }


def monthly_cost(cpu_cores: float, memory_gib: float, pricing: dict[str, float]) -> float:
    return (cpu_cores * pricing["cpu"] + memory_gib * pricing["memory"]) * 730.0


def read_cost_by_workload(kubecost_url: str, namespace: str) -> dict[str, float]:
    try:
        import requests  # noqa: PLC0415

        # <-- CHANGE THIS: endpoint path for per-workload allocation in your Kubecost/OpenCost version.
        # Valid values: /model/allocation with aggregate=controller,namespace or service-specific equivalent.
        # Find the endpoint shape in finops/docs/installation.md and your Kubecost API docs.
        resp = requests.get(
            f"{kubecost_url}/model/allocation",
            params={
                "window": "30d",
                "aggregate": "controller,namespace",
                "filter": f"namespace:{namespace}",
            },
            timeout=30,
        )
        resp.raise_for_status()
        payload = resp.json().get("data", [])
        allocations = payload[-1] if payload else {}
        result: dict[str, float] = {}
        for key, value in allocations.items():
            controller_name = key.split("/")[0] if "/" in key else key
            result[controller_name] = float(value.get("totalCost", 0.0))
        return result
    except Exception as exc:  # noqa: BLE001
        print(
            f"WARNING: workload-level Kubecost data unavailable ({exc}); using request-based estimate only.",
            file=sys.stderr,
        )
        return {}


def pdb_single_replica_warning(
    pdbs: list[dict[str, Any]], deployment: dict[str, Any]
) -> str | None:
    replicas = int(deployment.get("spec", {}).get("replicas", 1) or 1)
    if replicas != 1:
        return None
    dep_name = deployment.get("metadata", {}).get("name", "")
    pod_labels = (
        deployment.get("spec", {}).get("template", {}).get("metadata", {}).get("labels", {})
    )
    for pdb in pdbs:
        min_available = pdb.get("spec", {}).get("minAvailable")
        if str(min_available) != "1":
            continue
        selector = pdb.get("spec", {}).get("selector", {}).get("matchLabels", {})
        if not selector:
            continue
        if all(pod_labels.get(k) == v for k, v in selector.items()):
            return (
                "reducing resources on a single-replica workload with strict PDB may cause OOM kills during rollout"
                f" (deployment={dep_name}, pdb={pdb.get('metadata', {}).get('name', 'unknown')})"
            )
    return None


def check_bounds(target_cpu: float, target_mem: float, lower_cpu: float, lower_mem: float) -> bool:
    # Safety rule: never recommend below lower bound.
    return target_cpu >= lower_cpu and target_mem >= lower_mem


def build_candidate(
    namespace: str,
    vpa: dict[str, Any],
    deployment: dict[str, Any],
    pricing: dict[str, float],
    workload_costs: dict[str, float],
    allow_aggressive: bool,
    pdb_warning: str | None,
) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    dep_name = deployment["metadata"]["name"]
    containers = deployment["spec"]["template"]["spec"].get("containers", [])
    by_name = {c["name"]: c for c in containers}
    recs = vpa.get("status", {}).get("recommendation", {}).get("containerRecommendations", [])

    for rec in recs:
        cname = rec.get("containerName")
        if cname not in by_name:
            continue

        container = by_name[cname]
        requests = container.get("resources", {}).get("requests", {})
        limits = container.get("resources", {}).get("limits", {})
        current_cpu = parse_cpu(str(requests.get("cpu", "0")))
        current_mem = parse_memory_gib(str(requests.get("memory", "0")))
        current_limit_cpu = parse_cpu(str(limits.get("cpu", "0")))
        current_limit_mem = parse_memory_gib(str(limits.get("memory", "0")))

        target = rec.get("target", {})
        lower = rec.get("lowerBound", {})
        target_cpu = parse_cpu(str(target.get("cpu", "0")))
        target_mem = parse_memory_gib(str(target.get("memory", "0")))
        lower_cpu = parse_cpu(str(lower.get("cpu", "0")))
        lower_mem = parse_memory_gib(str(lower.get("memory", "0")))

        if not check_bounds(target_cpu, target_mem, lower_cpu, lower_mem):
            print(
                f"SKIP {dep_name}/{cname}: target below VPA lower bound (cpu={target_cpu}/{lower_cpu}, mem={target_mem}/{lower_mem})",
                file=sys.stderr,
            )
            continue

        if target_cpu >= current_cpu and target_mem >= current_mem:
            continue

        # Keep existing ratio whenever possible, defaulting to 2x requests.
        cpu_ratio = (
            (current_limit_cpu / current_cpu) if current_cpu > 0 and current_limit_cpu > 0 else 2.0
        )
        mem_ratio = (
            (current_limit_mem / current_mem) if current_mem > 0 and current_limit_mem > 0 else 2.0
        )
        rec_limit_cpu = max(target_cpu, target_cpu * cpu_ratio)
        rec_limit_mem = max(target_mem, target_mem * mem_ratio)

        # Safety rule: limits must not be lower than requests.
        if rec_limit_cpu < target_cpu or rec_limit_mem < target_mem:
            raise ValueError(
                f"invalid recommendation: limits below requests for {dep_name}/{cname}"
            )

        mem_limit_reduction = 0.0
        if current_limit_mem > 0:
            mem_limit_reduction = (current_limit_mem - rec_limit_mem) / current_limit_mem * 100.0
        warnings: list[str] = []
        if mem_limit_reduction > 50.0:
            warning = (
                f"memory limit reduction is {mem_limit_reduction:.1f}% (>50%) for {dep_name}/{cname}; "
                "use --allow-aggressive to include"
            )
            if not allow_aggressive:
                print(f"SKIP {warning}", file=sys.stderr)
                continue
            warnings.append(warning)

        if pdb_warning:
            warnings.append(pdb_warning)

        req_current_cost = monthly_cost(current_cpu, current_mem, pricing)
        req_recommended_cost = monthly_cost(target_cpu, target_mem, pricing)
        req_savings = max(0.0, req_current_cost - req_recommended_cost)

        workload_monthly = workload_costs.get(dep_name, req_current_cost)
        reduction_factor = req_savings / req_current_cost if req_current_cost > 0 else 0.0
        estimated_monthly_savings = workload_monthly * reduction_factor
        savings_pct = (
            (estimated_monthly_savings / workload_monthly * 100.0) if workload_monthly > 0 else 0.0
        )

        candidates.append(
            {
                "namespace": namespace,
                "deployment": dep_name,
                "container": cname,
                "vpa_name": vpa.get("metadata", {}).get("name", dep_name),
                "current": {
                    "cpu_request": requests.get("cpu", "0"),
                    "memory_request": requests.get("memory", "0"),
                    "cpu_limit": limits.get("cpu", "0"),
                    "memory_limit": limits.get("memory", "0"),
                },
                "recommended": {
                    "cpu_request": format_cpu(target_cpu),
                    "memory_request": format_memory_gib(target_mem),
                    "cpu_limit": format_cpu(rec_limit_cpu),
                    "memory_limit": format_memory_gib(rec_limit_mem),
                },
                "expected_monthly_savings_usd": round(estimated_monthly_savings, 2),
                "savings_pct": round(savings_pct, 1),
                "warnings": warnings,
                "evidence": f"kubectl get vpa {vpa.get('metadata', {}).get('name', dep_name)} -n {namespace} -o yaml",
            }
        )
    return candidates


def render_patch(item: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# Generated by finops/scripts/generate-optimization-pr.py",
            f"# VPA recommendation for {item['deployment']} in namespace {item['namespace']}",
            f"# Expected savings: ${item['expected_monthly_savings_usd']:.2f}/month ({item['savings_pct']}% reduction)",
            f"# Evidence: {item['evidence']}",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            f"  name: {item['deployment']}",
            f"  namespace: {item['namespace']}",
            "spec:",
            "  template:",
            "    spec:",
            "      containers:",
            f"        - name: {item['container']}",
            "          resources:",
            "            requests:",
            f"              cpu: \"{item['recommended']['cpu_request']}\"  # was: {item['current']['cpu_request']} (VPA target)",
            f"              memory: \"{item['recommended']['memory_request']}\"  # was: {item['current']['memory_request']} (VPA target)",
            "            limits:",
            f"              cpu: \"{item['recommended']['cpu_limit']}\"  # was: {item['current']['cpu_limit']} (ratio-preserving)",
            f"              memory: \"{item['recommended']['memory_limit']}\"  # was: {item['current']['memory_limit']} (ratio-preserving)",
            "",
        ]
    )


def write_kustomization(namespace_dir: Path, patch_files: list[str]) -> None:
    lines = [
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "",
        "# <-- CHANGE THIS: set the real base or overlay path that owns these deployments.",
        "# Valid values: a relative path to your manifests, for example ../../cd/kubernetes/_overlays/production.",
        "# Find the correct path in your team deployment layout under cd/kubernetes/.",
        "resources:",
        "  - ../../cd/kubernetes/_overlays/production",
        "",
        "patchesStrategicMerge:",
    ]
    lines.extend([f"  - {name}" for name in patch_files])
    namespace_dir.joinpath("kustomization.yaml").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def build_pr_description(
    items: list[dict[str, Any]], checklist_text: str, namespace: str, output_dir: Path
) -> str:
    total = round(sum(i["expected_monthly_savings_usd"] for i in items), 2)
    avg_pct = round(sum(i["savings_pct"] for i in items) / len(items), 1) if items else 0.0
    lines = [
        "# FinOps Optimization PR",
        "",
        "## Summary",
        f"- Namespace: {namespace}",
        f"- Workloads optimized: {len(items)}",
        f"- Expected monthly savings: ${total:.2f}",
        f"- Average reduction: {avg_pct}%",
        "",
        "## Change Table",
        "| Workload | Container | Current Requests | Recommended Requests | Current Limits | Recommended Limits | Est. Savings / Month | Savings % |",
        "|---|---|---|---|---|---|---:|---:|",
    ]
    for i in items:
        lines.append(
            "| {dep} | {container} | CPU {ccpu}, MEM {cmem} | CPU {rcpu}, MEM {rmem} | CPU {clcpu}, MEM {clmem} | CPU {rlcpu}, MEM {rlmem} | ${save:.2f} | {pct}% |".format(
                dep=i["deployment"],
                container=i["container"],
                ccpu=i["current"]["cpu_request"],
                cmem=i["current"]["memory_request"],
                rcpu=i["recommended"]["cpu_request"],
                rmem=i["recommended"]["memory_request"],
                clcpu=i["current"]["cpu_limit"],
                clmem=i["current"]["memory_limit"],
                rlcpu=i["recommended"]["cpu_limit"],
                rlmem=i["recommended"]["memory_limit"],
                save=i["expected_monthly_savings_usd"],
                pct=i["savings_pct"],
            )
        )

    lines.extend(["", "## Per-Workload Evidence and Diff"])
    for i in items:
        lines.append("")
        lines.append(f"### {i['deployment']} / {i['container']}")
        lines.append(f"- Evidence: `{i['evidence']}`")
        lines.append("- Current vs Recommended:")
        lines.append(
            f"  - Requests: CPU {i['current']['cpu_request']} -> {i['recommended']['cpu_request']}, Memory {i['current']['memory_request']} -> {i['recommended']['memory_request']}"
        )
        lines.append(
            f"  - Limits: CPU {i['current']['cpu_limit']} -> {i['recommended']['cpu_limit']}, Memory {i['current']['memory_limit']} -> {i['recommended']['memory_limit']}"
        )
        lines.append(f"  - Expected monthly savings: ${i['expected_monthly_savings_usd']:.2f}")
        if i["warnings"]:
            lines.append("- Warnings:")
            lines.extend([f"  - {warning}" for warning in i["warnings"]])

    lines.extend(
        [
            "",
            "## Apply Instructions",
            f"1. Review generated patches in `{output_dir}/{namespace}/`.",
            f"2. Apply in staging first: `kubectl apply -k {output_dir}/{namespace}/`.",
            "3. Monitor for 24h (OOMKilled pods, latency, and error rate).",
            "4. Promote to production after staging stability is confirmed.",
            "",
            "## FinOps PR Checklist",
            checklist_text.strip(),
            "",
        ]
    )
    return "\n".join(lines)


def write_savings_configmap(namespace: str, items: list[dict[str, Any]], dry_run: bool) -> None:
    total = round(sum(i["expected_monthly_savings_usd"] for i in items), 2)
    payload = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": "finops-optimization-savings", "namespace": "finops"},
        "data": {
            "namespace": namespace,
            "monthly_savings_usd": str(total),
            "last_generated_candidates": str(len(items)),
        },
    }
    if dry_run:
        print("DRY RUN: would update finops-optimization-savings ConfigMap with:")
        print(json.dumps(payload, indent=2))
        return
    proc = subprocess.run(
        ["kubectl", "apply", "-f", "-"], input=json.dumps(payload), text=True, capture_output=True
    )
    if proc.returncode != 0:
        print(
            f"WARNING: could not update optimization savings ConfigMap: {proc.stderr.strip()}",
            file=sys.stderr,
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate optimization patches and PR text from VPA recommendations"
    )
    parser.add_argument("--namespace", required=True, help="Namespace to analyze")
    parser.add_argument(
        "--min-savings",
        type=float,
        default=20.0,
        help="Minimum savings percentage required (default: 20%%)",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Preview output without writing files"
    )
    parser.add_argument(
        "--output-dir",
        default="./optimization-patches",
        help="Output directory (default: ./optimization-patches)",
    )
    parser.add_argument(
        "--allow-aggressive",
        action="store_true",
        help="Allow memory limit reductions >50%% for a single change",
    )
    parser.add_argument(
        "--kubecost-url", default=DEFAULT_KUBECOST_URL, help="Kubecost/OpenCost API URL"
    )
    args = parser.parse_args()

    try:
        vpas = fetch_vpas(args.namespace)
        pricing = fetch_pricing(args.kubecost_url)
        workload_costs = read_cost_by_workload(args.kubecost_url, args.namespace)
        pdbs = fetch_pdbs(args.namespace)
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: required kubectl command failed: {exc.stderr or exc}", file=sys.stderr)
        sys.exit(1)

    all_candidates: list[dict[str, Any]] = []
    for vpa in vpas:
        target_ref = vpa.get("spec", {}).get("targetRef", {})
        if target_ref.get("kind") != "Deployment":
            continue
        dep_name = target_ref.get("name")
        if not dep_name:
            continue
        try:
            deployment = fetch_deployment(args.namespace, dep_name)
        except subprocess.CalledProcessError:
            print(f"WARNING: deployment '{dep_name}' not found, skipping", file=sys.stderr)
            continue

        pdb_warning = pdb_single_replica_warning(pdbs, deployment)
        all_candidates.extend(
            build_candidate(
                args.namespace,
                vpa,
                deployment,
                pricing,
                workload_costs,
                args.allow_aggressive,
                pdb_warning,
            )
        )

    selected = [c for c in all_candidates if c["savings_pct"] >= args.min_savings]
    selected.sort(key=lambda item: item["expected_monthly_savings_usd"], reverse=True)

    if not selected:
        print("No optimization patches generated. No workload met the savings/safety thresholds.")
        sys.exit(0)

    output_dir = Path(args.output_dir)
    namespace_dir = output_dir / args.namespace

    if args.dry_run:
        print(f"DRY RUN: would generate {len(selected)} patch files under {namespace_dir}")
        for item in selected:
            print(
                f"- {item['deployment']}-{item['container']}: ${item['expected_monthly_savings_usd']:.2f}/mo ({item['savings_pct']}%)"
            )
            if item["warnings"]:
                for warning in item["warnings"]:
                    print(f"  WARNING: {warning}")
        write_savings_configmap(args.namespace, selected, dry_run=True)
        return

    namespace_dir.mkdir(parents=True, exist_ok=True)
    patch_files: list[str] = []
    for item in selected:
        patch_name = f"{item['deployment']}-resources.yaml"
        (namespace_dir / patch_name).write_text(render_patch(item), encoding="utf-8")
        patch_files.append(patch_name)

    write_kustomization(namespace_dir, patch_files)

    checklist = Path("finops/templates/pr-checklist.md").read_text(encoding="utf-8")
    pr_text = build_pr_description(selected, checklist, args.namespace, output_dir)
    (output_dir / "PR-DESCRIPTION.md").write_text(pr_text, encoding="utf-8")
    write_savings_configmap(args.namespace, selected, dry_run=False)

    total_savings = sum(i["expected_monthly_savings_usd"] for i in selected)
    print(f"Generated {len(selected)} patch files in {namespace_dir}")
    print(f"PR description written to {output_dir / 'PR-DESCRIPTION.md'}")
    print(f"Expected monthly savings: ${total_savings:.2f}")


if __name__ == "__main__":
    main()
